--- 
- hosts: all
  become: true 
  tasks: 
    
  - name: update and upgrade all the servers 
    apt: 
      update_cache: yes
      upgrade: yes

  - name: install apache2 server
    apt:
      name: 
        - apache2
      state: latest

  - name: set timezone to Africa/Lagos
    timezone: 
      name: Africa/Lagos


  - name: print the hostname on the server 
    shell: echo "<h1> This is the server name $(hostname -f)"</h1> > /var/www/html/index.html 
    
  - name: restart apache2 
    service: 
      name: apache2 
      state: restarted 
  